apiVersion: ai.sap.com/v1alpha1
kind: Deployment
metadata:
  name: gemini-deployment
spec:
  scenarioName: gemini-scenario
  executionName: gen-execution
  deploymentConfiguration:
    instanceType: standard
