apiVersion: ai.sap.com/v1alpha1
kind: Deployment
metadata:
  name: gemini-deployment
  labels:
    scenario.ai.sap.com/name: gemini-scenario
spec:
  executableId: gemini-backend-executable
  instanceCount: 1
