apiVersion: ai.sap.com/v1alpha1
kind: Executable
metadata:
  name: gemini-flash
spec:
  inputs:
    parameters:
      - name: prompt
        type: string
  outputs:
    results:
      type: string
  template:
    containers:
      - image: docker.io/akshay1p1/gemini-backend:f22e606158e0dfb497289e2f26449f0b4d1f22bf
        command: ["python", "src/handler.py"]
        args: ["--prompt", "{{inputs.parameters.prompt}}"]