apiVersion: ai.sap.com/v1beta1
kind: Executable
metadata:
  name: genai-flash
spec:
  inputs:
    parameters:
      - name: prompt
        type: string
  executable:
    image: docker.io/akshay1p1/gemini-backend:latest
    command: ["python", "src/handler.py"]
    args: ["--prompt", "{{inputs.parameters.prompt}}"]
    env:
      - name: LLM_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: genai-secret
            key: endpoint
      - name: LLM_AUTH_TOKEN
        valueFrom:
          secretKeyRef:
            name: genai-secret
            key: token
