apiVersion: ai.sap.com/v1alpha1
kind: Executable
metadata:
  name: gemini-flash
spec:
  inputs:
    parameters:
      - name: prompt
        type: string
  outputs:
    results:
      type: string
  template:
    containers:
      - image: docker.io/akshay1p1/gemini-backend:latest
        command: ["python", "src/handler.py"]
        args: ["--prompt", "{{inputs.parameters.prompt}}"]