apiVersion: ai.sap.com/v1beta1
kind: Executable
metadata:
  name: gemini-flash
spec:
  executable:
    image: docker.io/akshay1p1/gemini-backend:latest  # Using latest for simplicity
    command: ["python", "src/handler.py"]