apiVersion: ai.sap.com/v1beta1
kind: Executable
metadata:
  name: gemini-flash
spec:
  executable:
    image: docker.io/akshay1p1/gemini-backend:latest
    command: ["python", "src/handler.py"]
    env:
      - name: LLM_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: genai-secret
            key: endpoint
      - name: LLM_AUTH_TOKEN
        valueFrom:
          secretKeyRef:
            name: genai-secret
            key: token
