apiVersion: ai.sap.com/v1alpha1
kind: Executable  # ✅ This is the key
metadata:
  name: gemini-2.0-flash  # ✅ This MUST match what you want to select
spec:
  inputs:
    parameters:
      - name: prompt
        type: string
  outputs:
    - name: response
  template:
    containers:
      - image: docker.io/akshay1p1/gemini-backend:latest

        command: ["python", "src/handler.py"]
        args: ["--prompt", "{{prompt}}"]
